name: build and deploy aliyun

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Copy .env.example
        run: |
          cp .env.example .env
          mkdir -p /root/repo/github/home/
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy to aliyun server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          ARGS: "-avz --delete --verbose"
          EXCLUDE: "./node_modules/"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
          REMOTE_USER: "root"
          TARGET: "/root/repo/github/home/"
          SCRIPT_AFTER: "cd /root/repo/github/home && docker-compose down --rmi all && docker-compose up"
