name: build and deploy aliyun

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # 复制环境变量文件
      - name: Copy .env.example
        run: |
          cp .env.example .env
      # 安装依赖 build
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy to aliyun server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          ARGS: "-avz --delete --verbose"
          EXCLUDE: "/node_modules/"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
          REMOTE_USER: "root"
          TARGET: "/root/repo/github/"
      - name: Deploy with docker-compose
        run: |
          docker-compose down --rmi all
          docker-compose up
